<template>
    <div class="d-flex flex-col gap-4 pa-8">
        <c-progress-linear
            color="indigo"
            value="80"
            height="4"
        />
        <c-progress-linear
            color="teal"
            value="65"
            height="6"
        />
        <c-progress-linear
            color="deep-purple-lighten-1"
            value="50"
            height="8"
        />
        <c-progress-linear
            color="green-darken-1"
            value="90"
            height="10"
        />
        <c-progress-linear
            color="#FFA726"
            value="35"
            height="12"
        />
        <c-progress-linear
            color="#fa5a5a"
            value="20"
            height="14"
        />
    </div>
</template>
